### ISSUE TITLE
Find car data [*]

### ISSUE THREAD

**Issue by danielanatolie** [danielanatolie/mecollect#3]
Find a list of 30 cars with a few attributes that we can filter on.
*Please go for exotic cars >:D (ferrari, porsche, Mclauren, etc.)
Example:
Name      Price Model   Year      Brand    Motor Type etc. 
Haracun  1 mil   T40      2008    Lambo    v7

Put it all in a folder called data/cardata.txt

**Comment by amford** [comment]
Done, committed to my branch.
